[tool.semantic_release]

# The branch from which releases will be made
branch = "main"

# Locations of version variables to update during release
version_variable = """
README.rst:Version,
version.toml:__version__,
docs/source/conf.py:__version__
"""

# Optional build command to run before release (leave empty if not needed)
build_command = ""

# Whether to remove the `dist` directory before building
remove_dist = true

# Whether to upload the release artifacts to GitHub Releases
upload_to_release = true

# Treat major versions starting from 0 as minor increments
major_on_zero = true

# Disable uploading the release to PyPI
upload_to_pypi = false

# Skip build status checks
check_build_status = false

# Custom commit subject for version bumps
commit_subject = ":memo: build(version): Bump to version - {version}."
