# Generated by Django 5.1.3 on 2024-12-15 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('bank_account_statement', models.FileField(upload_to='parent/kyc/bank_account_statement/')),
                ('id_type', models.CharField(choices=[('National ID', 'National ID'), ('International Passport', 'International Passport'), ('Driver License', 'Driver License'), ('Voter Card', 'Voter Card')], max_length=50)),
                ('id_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('id_front', models.FileField(blank=True, null=True, upload_to='parent/kyc/id_front/')),
                ('id_back', models.FileField(blank=True, null=True, upload_to='parent/kyc/id_back/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='customer.parents')),
            ],
            options={
                'verbose_name': 'Parent KYC',
                'verbose_name_plural': 'Parent KYC',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customer.parents')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.schoolclass')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
