# Generated by Django 5.1.3 on 2024-12-17 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='school.schoolclass'),
        ),
        migrations.CreateModel(
            name='ParentCreditCapacityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_score_description', models.CharField(max_length=50)),
                ('capacity_score_description', models.CharField(max_length=50)),
                ('credit_score_recommendation', models.TextField()),
                ('capacity_score_recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_capacity_score', to='customer.parents')),
            ],
            options={
                'verbose_name': 'Parent Credit and Capacity Score',
                'verbose_name_plural': 'Parent Credit and Capacity Scores',
                'ordering': ['parent__user__first_name', 'parent__user__last_name'],
            },
        ),
    ]
